function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 14-Feb-2025 11:19:18
fileToRead1 = "C:\Users\atjensvo\cernbox\Documents\GitHub\MasterThesis\MATLAB\GlobDesOpt-master\examples\Results_Matlab_ga\accept_60\ParamsOpt.mat";
% Import the file
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
    disp(newData1.(vars{i}))
end


